### ISSUE TITLE
Machine readable release descriptions

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/release#4]
As a consumer of the Stackable products I'd like to have machine readable descriptions available on what's in a specific platform release.

This is done when
- [ ] there is a file available for each platform release which includes the components it contains (i.e. the operator versions)
- [ ] the file should be downloadable via HTTPS without login

I am not sure if we want to have one big file or one file per release, I also don't know if this can be done as part of the SBOM work that we plan to do or if we should invent our own format.

@hikhvar Any opinions?

**Comment by razvan** [comment]
It seems to me like SBOM is what we want in the long run.

## Articles

* Software Bill Of Materials: Formats, Use Cases, and Tools https://fossa.com/blog/software-bill-of-materials-formats-use-cases-tools/
* A Survey of existing SBOM formats and standards: https://www.ntia.gov/files/ntia/publications/ntia_sbom_formats_and_standards_whitepaper_-_version_20191025.pdf
* 
## Standards
* Linux Foundation Software Package Exchange : https://spdx.github.io/spdx-spec/
* Cyclone DX : https://github.com/CycloneDX/specification

**Comment by lfrancke** [comment]
Good question: For now let's just have a very simple description of a release and decouple it from SBOM.
We can later add a link to our SBOM information in the metadata.

**Comment by sbernauer** [comment]
At the moment i needed to "invent" a format for `stackablectl release list` and `stackablectl release install 20.04`
It looks as follows, appreciate any feedback
It may seem a little bit overkill putting `operatorVersion` behind a map structure but by doing so we could easily also add an `recommendedVersion` in the future.
Invocation looks as follows at the moment
```
$ stackablectl release list
RELEASE            RELEASE DATE   DESCRIPTION
22.04-sbernauer    2022-04-26     Test release from sbernauer to demonstrate stackablectl
alpha-3            2022-02-14     Second release which added Airflow, Druid and Superset
alpha-2            2021-10-29     First release of the Stackable Data Platform

$ stackablectl release install 22.04-sbernauer
[...]
```

```
---
releases:
  22.04-sbernauer:
    releaseDate: 2022-04-26
    description: Test release from sbernauer to demonstrate stackablectl
    products:
      airflow:
        operatorVersion: 0.2.0
      commons:
        operatorVersion: 0.1.0-nightly # TODO Change to 0.1.0 when available
      druid:
        operatorVersion: 0.5.0
      hbase:
        operatorVersion: 0.2.0
      hdfs:
        operatorVersion: 0.3.0
      hive:
        operatorVersion: 0.5.0
      kafka:
        operatorVersion: 0.5.0
      nifi:
        operatorVersion: 0.5.0
      opa:
        operatorVersion: 0.8.0
      secret:
        operatorVersion: 0.2.0
      spark:
        operatorVersion: 0.5.0
      spark-k8s:
        operatorVersion: 0.1.0-nightly # TODO Change to 0.1.0 when available
      superset:
        operatorVersion: 0.4.0
      trino:
        operatorVersion: 0.3.1
      zookeeper:
        operatorVersion: 0.9.0
  alpha-3:
    releaseDate: 2022-02-14
    description: Second release which added Airflow, Druid and Superset
    products:
      airflow:
        operatorVersion: 0.2.0
      druid:
        operatorVersion: 0.4.0
      hbase:
        operatorVersion: 0.2.0
      hdfs:
        operatorVersion: 0.3.0
      hive:
        operatorVersion: 0.5.0
      kafka:
        operatorVersion: 0.5.0
      nifi:
        operatorVersion: 0.5.0
      opa:
        operatorVersion: 0.8.0
      regorule:
        operatorVersion: 0.6.0
      secret:
        operatorVersion: 0.2.0
      spark:
        operatorVersion: 0.5.0
      superset:
        operatorVersion: 0.3.0
      trino:
        operatorVersion: 0.3.1
      zookeeper:
        operatorVersion: 0.9.0
```
